name: install_dependencies
runs:
  using: composite
  steps:
    - name: clone daemon
      run: git clone https://github.com/bitcart/bitcart $HOME/bitcart-daemon
      shell: bash
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Install library
      run: |-
        uv sync --frozen --compile-bytecode
        echo "$PWD/.venv/bin" >> $GITHUB_PATH
      shell: bash
    - name: install daemon
      run: |-
        apt update
        apt install libsecp256k1-dev -y
        cd $HOME/bitcart-daemon
        uv pip install -U -r requirements/base.txt
        uv pip install -U -r requirements/daemons/btc.txt
      shell: bash
