name: test_and_deploy
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        v:
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        version: ${{ matrix.v }}
      - uses: "./.github/actions/install_dependencies"
      - name: prepare daemon
        run: |-
          cd ~/bitcart-daemon
          make testnet &
      - name: run fast tests
        run: make ci
      - uses: "./.github/actions/upload-results"
